apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rlkf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rlkf
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rlkf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rlkf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rlkf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bndp-tenant/rhtap-demo-app/hacbs-test-project-rlkf@sha256:d7c3e130c5d14b1364309317466427e26bd35cf528e9a690e8b7ed09fd4661e4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
