apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rlkf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bndp-tenant/rhtap-demo-app/hacbs-test-project-rlkf@sha256:d7c3e130c5d14b1364309317466427e26bd35cf528e9a690e8b7ed09fd4661e4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
